<?php include 'header.php';?>
  <div class="container">
    <div class="termosEcondicoes">
      <br><br><br>
      <p style="font-weight:bold;text-transform:uppercase;font-size:18px;">Termos e Condições</p>

      <p style="font-weight:bold;text-transform:uppercase;">Informação Geral</p>
      <p>1. O presente website o “https//:www.azenhaguesthouse.com”, é propriedade exclusiva da Azenha GuestHouse Unipessoal Lda, com sede na Rua da Azenha N 7, Foz do Arelho, PT 2500 450 Portugal, matriculada sob o número único de matrícula e de pessoa coletiva <b>((ISABEL: FALTA COLOCAR NUMERO  EX: 509298435))</b>e com o capital social integralmente subscrito e realizado de  <b>((ISABEL: FALTA COLOCAR NUMERO  EX: 25.000 €))</b>.</p>
      <p>2. Por favor, leia com atenção os seguintes termos e condições de utilização (os "Termos e Condições") e a política de privacidade (a “Política de Privacidade”) antes de utilizar este Website. O acesso e a utilização deste Website são regidas pelos presentes Termos e Condições e pela Política de Privacidade, bem como pela legislação em vigor em Portugal, sendo o cumprimento das respetivas regras da inteira responsabilidade do Utilizador.</p>
      <p>3. Ao aceder, navegar ou utilizar o presente Website, o Utilizador reconhece que leu, compreendeu e está de acordo com estes Termos e Condições e com a Política de Privacidade aplicável ao mesmo. A Azenha GuestHouse reserva-se o direito de alterar os Termos e Condições ou rever a Politica de Privacidade sem aviso prévio, sendo da responsabilidade do Utilizador ler e rever os mesmos sempre que aceda ao Website.</p>
      <p>4. Para qualquer esclarecimento sobre o teor dos Termos e Condições ou da Política de Privacidade, deve o Utilizador contactar a Azenha GuestHouse, podendo, para esse fim, utilizar um dos seguintes contactos:</p>
      <p>por carta para a morada: Rua da Azenha N 7, Foz do Arelho, PT 2500 450 Portugal</p>
      <p>ou por telefone através do nº: 351 96 58 68 037</p>
      <p>5. Sem prejuízo de outras sanções previstas na lei ou nos presentes Termos e Condições, o incumprimento por parte do Utilizador de qualquer regra de utilização resultará na cessação automática de todos os respetivos direitos que lhe tenham sido concedidos, tendo o Utilizador ainda a obrigação de destruir imediatamente todas as cópias de materiais descarregados ou impressos que estejam na sua posse ou controlo.</p><br><br>

      <p style="font-weight:bold;text-transform:uppercase;">Direitos de Propriedade Intelectual</p>
      <p>6. Os conteúdos deste Website estão protegidos pela legislação portuguesa e internacional em matéria de propriedade intelectual e industrial. Salvo casos pontuais devidamente indicados, a Azenha GuestHouse é proprietária ou detentora de uma licença de exploração sobre todos os conteúdos que compõem o presente Website, incluindo o nome de domínio www.azenhaguesthouse.com, www.azenhaguesthouse.com, www.azenhaguesthouse.com, a marca Azenha GuestHouse e a marca “Azenha Home” e todos os outros desenhos, logótipos, textos, imagens, e materiais áudio e de vídeo. Não é permitido, inclusivamente, exibir, reproduzir, distribuir, modificar, transmitir ou usar os conteúdos de forma alguma, para nenhum propósito público ou comercial sem o prévio e expresso consentimento por escrito da Azenha GuestHouse Unipessoal Lda. O Utilizador pode, no entanto, copiar ou imprimir páginas do presente Website desde que as mesmas não sejam alteradas de maneira alguma, sejam destinadas a fins estritamente pessoais, e desde que as referências à fonte e às outras menções de reserva de direitos de autor não forem removidas.</p>
      <p>7. Qualquer informação ou outro conteúdo que o Utilizador transmita para este Website, seja através de correio electrónico, mensagem para grupo de discussão, envio de ficheiros ou de outro modo, será considerado como não confidencial e não reservado. Ao transmitir conteúdos para este Website, o Utilizador aceita que a Azenha GuestHouse Unipessoal lda, poderá utilizá-los para os fins que entender, sem a necessidade de qualquer consentimento expresso do Utilizador.</p>
      <p>8. Está expressamente proibida a utilização deste Website para fins ilegais ou quaisquer outros fins que possam ser considerados prejudiciais para a imagem das marcas Azenha GuestHouse e Azenha Home. A usurpação, contrafação, aproveitamento do conteúdo usurpado ou contrafeito, a identificação ilegítima e a concorrência desleal serão punidas cível ou criminalmente.</p><br><br>

      <p style="font-weight:bold;text-transform:uppercase;">Garantias e Limitação da Responsabilidade</p>
      <p>9. A Azenha GuestHouse Unipessoal Lda, faculta o conteúdo presente neste Website exclusivamente para informação geral e não garante a sua exactidão, qualidade, precisão, atualidade ou integridade. O acesso e a navegação do presente Website são realizados por conta e risco do Utilizador e não estabelece qualquer espécie de relação contratual entre este e a Azenha GuestHouse Unipessoal Lda.</p>
      <p>10. A Azenha GuestHouse Unipessoal Lda não garante que o acesso a este Website seja ininterrupto ou isento de erros, vírus ou de outro material prejudicial ou que o servidor onde se encontra alojado esteja livre de vírus ou qualquer outro agente nocivo.</p>
      <p>11. A Azenha GuestHouse Unipessoal Lda reserva-se o direito de realizar alterações e correções, suspender ou encerrar o Website quando considerar apropriado, sem necessidade de pré-aviso a qualquer Utilizador ou entidade. A Azenha GuestHouse Unipessoal Lda não assume qualquer responsabilidade pelos prejuízos decorrentes de eventuais situações de impossibilidade, atraso, suspensão ou interrupção no acesso ao Website em virtude de falhas técnicas ou outros motivos.</p>
      <p>12. O Utilizador concorda em não transmitir a este Website conteúdos ilícitos, ameaçadores, acusatórios, difamatórios, obscenos, escandalosos, pornográficos, profanos, ou quaisquer outros que possam constituir ou encorajar condutas ilícitas. A Azenha GuestHouse Unipessoal Lda esclarece que não filtra nem monitoriza previamente os conteúdos transmitidos a este Website por utilizadores/terceiros. No entanto, caso venha a ser notificada da existência de algum conteúdo ilícito ou inapropriado no Website, a Azenha GuestHouse Unipessoal Lda pode investigar a alegação e determinar a remoção do respectivo conteúdo.</p>
      <p>13. Este Website contém ligações (“links”) para websites de internet de terceiros. Estes “links” são fornecidos unicamente para a conveniência e acessibilidade do Utilizador. A Azenha GuestHouse Unipessoal Lda não endossa o conteúdo de qualquer desses websites de internet e não é responsável pelo conteúdo dos mesmos, nomeadamente a exactidão e atualização dos conteúdos, as políticas de privacidade ou as respectivas condições de utilização. O acesso e visita a qualquer desses websites de internet de terceiros correm por inteiro risco do utilizador. Compete ao Utilizador tomar as devidas precauções para se proteger contra vírus, “worms”, “trojans horses” e outros programas potencialmente destrutivos, bem como para proteger as respetivas informações, conforme considerar apropriado.</p>
      <p>14. A Azenha GuestHouse Unipessoal Lda cooperará plenamente com todas as autoridades competentes para fiscalizar e aplicar a Lei, podendo, inclusivamente, revelar a identidade do Utilizador ou ajudar a identificar e/ou localizar qualquer pessoa que seja procurado pelas referidas autoridades.</p><br><br>

      <p style="font-weight:bold;text-transform:uppercase;">Seguança</p>
      <p>15. Poderão existir áreas deste Website que carecem do registo do Utilizador. Com vista a salvaguardar a proteção da privacidade e segurança no acesso aos dados do Utilizador, este deverá criar e introduzir, em campos específicos, o seu “login” e senha secreta, o que lhe possibilitará o acesso exclusivo à área reservada a clientes. O “login” e senha secreta são pessoais e intransmissíveis e não devem ser partilhadas com terceiros. A Azenha GuestHouse Unipessoal Lda deverá ser informada imediatamente da perda ou furto dos códigos de acesso à área reservada do presente Website ou de qualquer uso não autorizado que for detetado. A Azenha GuestHouse Unipessoal Lda reserva-se o direito de, sem aviso, eliminar qualquer “login” e senha que dê acesso à área reservada do Website, caso haja indícios de violação de privacidade e segurança.</p>
      <p>16. O Utilizador compromete-se a não interferir ou tentar interferir com o bom funcionamento deste Website, nem aceder ou tentar aceder, sem permissão para tal, a dados que não lhe pertencem.</p>
      <p>17. Quaisquer tentativas de alteração de informação, de carregamento de informação, ou de qualquer outra acção que possa causar dano ou pôr em risco a integridade do sistema serão punidas de acordo com a legislação em vigor.</p>
      <p>18. O Utilizador mais reconhece e aceita que a Azenha GuestHouse Unipessoal Lda poderá monitorizar ou autorizar um terceiro a monitorizar os acessos a este Website a fim de detectar a pratica de actividades ilícitas, nomeadamente os crimes informáticos previstos na Lei n.º 109/2009, de 15 de Setembro (Lei do Cibercrime).</p><br><br>
    </div>
  </div>
<?php include 'footer.php';?>
